require: rubocop-rails

Metrics/AbcSize:
  Enabled: false
  Exclude:
    - 'db/migrate/*'
    - 'app/controllers/dashboards_controller.rb'
    - 'lib/tasks/*'
    - 'db/eeds.rb'

Naming/VariableNumber:
  EnforcedStyle: 'snake_case'
  Exclude:
    - '**/*' # Exclude everything initially
  Include:
    - '**/*' # Include everything
  Ignore:
    - 'google_oauth2'

Metrics/BlockLength:
  Exclude:
    - 'config/environments/*'
    - 'config/routes.rb'
    - 'config/routes/*'
    - 'lib/tasks/*'
    - 'app/models/concerns/omniauthable.rb'

Rails/UnknownEnv:
  Environments:
    - production
    - staging
    - development
    - test

Metrics/CyclomaticComplexity:
  Exclude:
    - 'bin/*'
    - 'app/controllers/clients/dashboards_controller.rb'
    - 'app/controllers/clients/dashboards/businesses_controller.rb'
    - 'app/controllers/omniauth_sessions_controller.rb'
    - 'app/controllers/clients/dashboards/qrs/reviews_controller.rb'
    - 'app/controllers/clients/dashboards/businesses/approvals_controller.rb'
    - 'app/controllers/qr_codes_controller.rb'
    - 'app/controllers/clients/webhooks_controller.rb'
    - 'app/controllers/clients/dashboards/tool_marketings/*'
    - 'app/controllers/riders/brands/downvotes_controller.rb'
    - 'app/controllers/riders/brands/upvotes_controller.rb'

Metrics/MethodLength:
  Enabled: false
  Exclude:
    - 'db/migrate/*'
    - 'bin/*'

Metrics/PerceivedComplexity:
  Exclude:
    - 'db/migrate/*'
    - 'bin/*'
    - 'app/controllers/clients/dashboards_controller.rb'
    - 'app/controllers/clients/dashboards/businesses_controller.rb'
    - 'app/controllers/omniauth_sessions_controller.rb'
    - 'app/controllers/clients/dashboards/businesses/approvals_controller.rb'
    - 'app/controllers/clients/webhooks_controller.rb'
    - 'app/controllers/clients/dashboards/tool_marketings/*'
    - 'app/controllers/clients/dashboards/tool_moodboards/*'
    - 'app/controllers/riders/brands/downvotes_controller.rb'
    - 'app/controllers/riders/brands/upvotes_controller.rb'

Style/Documentation:
  Enabled: false
  Exclude:
    - 'db/migrate/*'
    - 'bin/*'
    - 'test/*'

Style/IfUnlessModifier:
  Exclude:
    - 'bin/*'

Style/ClassAndModuleChildren:
  Enabled: false

Layout/LineLength:
  Exclude:
    - 'bin/*'
    - 'db/seeds.rb'
    - 'app/models/review.rb'
    - 'app/models/business.rb'
    - 'app/controllers/clients/dashboards/tool_moodboards_controller.rb'
    - 'app/controllers/clients/dashboards/tool_marketings/*'
    - 'app/controllers/clients/dashboards/tool_moodboards/*'

Rails/LexicallyScopedActionFilter:
  Enabled: false

Metrics/ClassLength:
  Exclude:
    - 'test/**/*.rb'
    - 'app/controllers/clients/dashboards/tool_marketings/*'
    - 'app/controllers/clients/webhooks_controller.rb'