version: "3.1"
name: regeular

services:
  web:
    environment:
      - REGEULAR_DATABASE_HOST=${REGEULAR_DATABASE_HOST}
      - REGEULAR_DATABASE_USERNAME=${REGEULAR_DATABASE_USERNAME}
      - REGEULAR_DATABASE_PASSWORD=${REGEULAR_DATABASE_PASSWORD}
      - REDIS_URL=${REDIS_URL}
      - RAILS_ENV=${RAILS_ENV}
      - RAILS_MASTER_KEY=${RAILS_MASTER_KEY}
    build:
      context: ../../../../
      dockerfile: ./deploy/docker/environment/distribution/Dockerfile
    ports:
      - "3000:3000"