version: "3.1"
name: regeular_local

services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: true
    ports:
      - "3306:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 3s
      retries: 10
  web:
    environment:
      - REGEULAR_DATABASE_HOST=${REGEULAR_DATABASE_HOST}
      - REGEULAR_DATABASE_USERNAME=${REGEULAR_DATABASE_USERNAME}
      - REGEULAR_DATABASE_PASSWORD=${REGEULAR_DATABASE_PASSWORD}
      - REDIS_URL=${REDIS_URL}
      - RAILS_ENV=${RAILS_ENV}
    build:
      context: ../../../../
      dockerfile: ./deploy/docker/environment/development/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ../../../../:/app
    depends_on:
      db:
        condition: service_healthy
